---
abstract: 'A New Way to Make Modules'
author:
  - 'Ingy döt Net'
build_requires:
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Module-MakeMaker
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  File::Find::Rule: 0.30
  File::ShareDir: 0
  Template::Toolkit::Simple: 0
  YAML::XS: 0
  perl: 5.8.3
version: 0.01
